services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10550:10550"
    volumes:
      - .:/chickeam 
      - /chickeam/node_modules
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - frontend

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chickeam"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - "20550"
    networks:
      - frontend

volumes:
  db_data:

networks:
  frontend:
    driver: bridge

# mysql

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3000:3000"
#     volumes:
#       - .:/chickeam 
#       - /chickeam/node_modules
#     environment:
#       NODE_ENV: development
#       DATABASE_URL: mysql://chickeam:1234@db:3306/mydatabase
#     depends_on:
#       db:
#         condition: service_healthy
        

#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: kinmha112
#       MYSQL_DATABASE: mydatabase
#       MYSQL_USER: chickeam
#       MYSQL_PASSWORD: 1234
#       MYSQL_TCP_PORT: 3306
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     ports:
#       - "3306:3306"
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pkinmha112"]
#       interval: 5s
#       timeout: 5s
#       retries: 10


# volumes:
#   db_data:

