services:
  nginx:
    image: alfg/nginx-rtmp
    container_name: nginx-rtmp
    ports:
      - "40550:40550"
      - "50550:50550"
      - "60550:60550"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf.template
      - ./wwwroot:/var/www/html
      - ./wwwroot/streaming:/opt/data/hls
    depends_on:
      - php
      - redis

  php:
    build: ./php
    container_name: php-fpm
    volumes:
      - ./wwwroot:/var/www/html
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "30550:30550"

  ffmpeg:
    image: jrottenberg/ffmpeg:4.3-alpine
    container_name: ffmpeg
    depends_on:
      - nginx
    stdin_open: true
    tty: true

